### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by blowsie** [unindented/grunt-sharp#2]
My environment

```
npm: 2.7.4
node : v0.12.2
windows: 8.1
```

When installing grunt-sharp I get the following error

```
D:\Projects\xxx>npm install grunt-sharp
\
> sharp@0.9.3 install D:\Projects\xxx\node_modules\grunt-sharp\node_modules\sharp
> node-gyp rebuild


D:\Projects\xxx\node_modules\grunt-sharp\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\.
.\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
The system cannot find the path specified.
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\xxxs\node_modules\grunt-sharp\node_modules\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-sharp" "-debug"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.9.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\xxx\npm-debug.log
```

Any idea what's going on here?

Im happy to test / provide additional information.

**Comment by blowsie** [comment]
https://github.com/lovell/sharp/issues/19

**Comment by blowsie** [comment]
Oops, I forgot I ran into this before.
https://github.com/lovell/sharp/issues/19

**Comment by unindented** [comment]
:+1:

**Comment by lovell** [comment]
sharp v0.10.0 now available with [support for Windows](https://github.com/lovell/sharp#windows).

**Comment by unindented** [comment]
@lovell awesome!
