### ISSUE TITLE
node 0.12 selft register error

### ISSUE THREAD

**Issue by ali-bugdayci** [unindented/grunt-sharp#3]
Getting the sharp loading error on node version 0.12:

```
grunt 
Loading "sharp.js" tasks...ERROR
>> Error: Module did not self-register.
```

**Comment by unindented** [comment]
Travis-CI seems to be fine with node 0.12 and grunt-sharp: https://travis-ci.org/unindented/grunt-sharp/jobs/58607424

Can you use the [`sharp` npm module](https://www.npmjs.com/package/sharp) by itself? If that's not the case, then your problem is with that module, not this one.

**Comment by ali-bugdayci** [comment]
Well when I saw the module did not self register, I thought grunt tasks being load by default if npm starts with "grunt-*"

But after your comment I ran the grunt task verbose, and as you have said the cause might be sharp module:

```
Registering "grunt-sharp" local Npm module tasks.
Reading /home/bor/sunucu/mdm-server/node_modules/grunt-sharp/package.json...OK
Parsing /home/bor/sunucu/mdm-server/node_modules/grunt-sharp/package.json...OK
Loading "sharp.js" tasks...ERROR
>> Error: Module did not self-register.
>>     at Error (native)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/home/bor/sunucu/mdm-server/node_modules/grunt-sharp/node_modules/sharp/index.js:11:13)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.module.exports (/home/bor/sunucu/mdm-server/node_modules/grunt-sharp/tasks/sharp.js:8:15)
>>     at loadTask (/home/bor/sunucu/mdm-server/node_modules/grunt/lib/grunt/task.js:325:10)
>>     at /home/bor/sunucu/mdm-server/node_modules/grunt/lib/grunt/task.js:361:7
>>     at Array.forEach (native)
```

I will link the issue here. Thanks
