### ISSUE TITLE
Issues when running grunt tasks from Jenkins

### ISSUE THREAD

**Issue by blowsie** [unindented/grunt-sharp#5]
For some reason, I get the following error when I run grunt-sharp from my CI system, Jenkins.
Any ideas what might be causing this?

```
08:51:35 Parsing D:\Builds\xxx\node_modules\grunt-sharp\package.json...OK
08:51:35 Loading "sharp.js" tasks...ERROR
08:51:35 >> Error: error: 126D:\Builds\xxx\node_modules\grunt-sharp\node_modules\sharp\build\Release\sharp.node
08:51:35 >>     at Error (native)
08:51:35 >>     at Module.load (module.js:355:32)
08:51:35 >>     at Function.Module._load (module.js:310:12)
08:51:35 >>     at Module.require (module.js:365:17)
08:51:35 >>     at require (module.js:384:17)
08:51:35 >>     at Object.<anonymous> (D:\Builds\xxx\node_modules\grunt-sharp\node_modules\sharp\index.js:12:13)
08:51:35 >>     at Module._compile (module.js:460:26)
08:51:35 >>     at Object.Module._extensions..js (module.js:478:10)
08:51:35 >>     at Module.load (module.js:355:32)
08:51:35 >>     at Function.Module._load (module.js:310:12)
08:51:35 >>     at Module.require (module.js:365:17)
08:51:35 >>     at require (module.js:384:17)
08:51:35 >>     at Object.module.exports (D:\Builds\xxx\node_modules\grunt-sharp\tasks\sharp.js:8:15)
08:51:35 >>     at loadTask (D:\Builds\xxx\node_modules\grunt\lib\grunt\task.js:325:10)
08:51:35 >>     at D:\Builds\xxx\node_modules\grunt\lib\grunt\task.js:361:7
08:51:35 >>     at Array.forEach (native)
```

**Comment by blowsie** [comment]
Oh, by the way, running the same task from command line in the same folder works perfectly

**Comment by unindented** [comment]
@blowsie I haven't encountered that error before. It looks like the error is being thrown by `sharp` (`node_modules\grunt-sharp\node_modules\sharp\build\Release\sharp.node`), not `grunt-sharp`, so you'll probably have more luck asking there: https://github.com/lovell/sharp

**Comment by blowsie** [comment]
Will do, thanks
